# Site settings
title: Takagotch
subtitle: "Journal of Takagotch"
email: m.me/tkgcci
description: "Make the footer happy by entering a short description about yourself here"
baseurl: "https://takagotch.github.io/page50"
url: "https://takagotch.github.io/page50"
twitter_username: "takagotch"
github_username:  "takagotch"
instagram_username: "takagotch"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
