# Site settings
title: Takagotch
subtitle: "Journal of [name]"
email: your-email@domain.com
description: "Make the footer happy by entering a short description about yourself here"
baseurl: ""
url: "https://takagotch.github.io/page50/"
twitter_username: "takagotch"
github_username:  "takagotch"
instagram_username: "takagotch"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
